import React, {useState} from 'react';
import {
  StyleSheet,
  Text,
  TouchableOpacity,
  View,
} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import AsyncStorage from '@react-native-async-storage/async-storage';
import {tokens} from '../theme/tokens';
import {STORAGE_KEYS} from '../storage/keys';
import type {NativeStackScreenProps} from '@react-navigation/native-stack';
import type {RootStackParamList} from '../navigation/RootNavigator';

type Props = NativeStackScreenProps<RootStackParamList, 'Tutorial'>;

const SLIDES = [
  {
    icon: '📰',
    headline: 'Read smarter, ask better',
    body: 'Most of us accept what we read. This app helps you push back — with the right questions.',
  },
  {
    icon: '🔗',
    headline: 'Paste a link, get questions',
    body: 'Share any article URL and the app generates 3 sharp questions to help you read more critically.',
  },
  {
    icon: '⚡',
    headline: 'Three ways to dig deeper',
    body: 'Quick — fast questions. Curious — more pointed. Answers — cues to find better information.',
  },
  {
    icon: '›',
    headline: 'Tap › to see why',
    body: 'Each card expands to show the reasoning behind the question and highlights the relevant passage.',
  },
  {
    icon: '🤖',
    headline: 'Powered by AI',
    body: 'Questions are generated by AI — a starting point for thinking, not a final verdict. Tap ⚑ to report anything that seems off.',
  },
];

export function TutorialScreen({navigation, route}: Props) {
  const [currentIndex, setCurrentIndex] = useState(0);
  const fromHome = route.params?.fromHome ?? false;
  const isLast = currentIndex === SLIDES.length - 1;
  const slide = SLIDES[currentIndex];

  async function complete() {
    await AsyncStorage.setItem(STORAGE_KEYS.TUTORIAL_SEEN, '1');
    if (fromHome) {
      navigation.goBack();
    } else {
      navigation.reset({index: 0, routes: [{name: 'Home'}]});
    }
  }

  return (
    <SafeAreaView style={styles.root}>
      {/* Top row: dots + skip */}
      <View style={styles.topRow}>
        <View style={styles.dots} accessibilityElementsHidden>
          {SLIDES.map((_, i) => (
            <View key={i} style={[styles.dot, i === currentIndex && styles.dotActive]} />
          ))}
        </View>
        {!isLast && (
          <TouchableOpacity
            onPress={complete}
            accessibilityRole="button"
            accessibilityLabel="Skip tutorial"
            accessibilityHint="Skips the tutorial and goes to the home screen"
            hitSlop={{top: 12, bottom: 12, left: 12, right: 12}}>
            <Text style={styles.skip}>Skip</Text>
          </TouchableOpacity>
        )}
      </View>

      {/* Slide content */}
      <View
        style={styles.content}
        accessible={true}
        accessibilityLiveRegion="polite"
        accessibilityLabel={`Slide ${currentIndex + 1} of ${SLIDES.length}: ${slide.headline}. ${slide.body}`}>
        <Text style={styles.icon} accessible={false}>{slide.icon}</Text>
        <Text style={styles.headline}>{slide.headline}</Text>
        <Text style={styles.body}>{slide.body}</Text>
      </View>

      {/* Next / Get started */}
      <View style={styles.bottomRow}>
        <TouchableOpacity
          style={styles.btn}
          onPress={isLast ? complete : () => setCurrentIndex(i => i + 1)}
          accessibilityRole="button"
          accessibilityLabel={isLast ? 'Get started' : 'Next slide'}>
          <Text style={styles.btnText}>
            {isLast ? 'Get started →' : 'Next →'}
          </Text>
        </TouchableOpacity>
      </View>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: tokens.bg,
    paddingHorizontal: 28,
  },
  topRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 20,
    paddingBottom: 8,
  },
  dots: {
    flexDirection: 'row',
    gap: 6,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: tokens.border,
  },
  dotActive: {
    backgroundColor: tokens.yellow,
  },
  skip: {
    color: tokens.muted,
    fontSize: 14,
  },
  content: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 20,
  },
  icon: {
    fontSize: 56,
    lineHeight: 68,
  },
  headline: {
    color: tokens.fg,
    fontSize: 22,
    fontWeight: '700',
    textAlign: 'center',
    lineHeight: 30,
  },
  body: {
    color: tokens.muted,
    fontSize: 15,
    lineHeight: 22,
    textAlign: 'center',
  },
  bottomRow: {
    paddingBottom: 32,
  },
  btn: {
    backgroundColor: tokens.yellow,
    borderRadius: tokens.radiusPill,
    paddingVertical: 14,
    alignItems: 'center',
  },
  btnText: {
    color: '#000',
    fontSize: 15,
    fontWeight: '700',
  },
});
